server {

    listen 80;
    listen [::]:80;

    server_name {{DOMAIN}} www.{{DOMAIN}};

    root {{WEBROOT}}/public;
    index index.php index.html index.htm;

    access_log {{WEBROOT}}/logs/access.log;
    error_log  {{WEBROOT}}/logs/error.log;

    client_max_body_size 128M;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|svg|webp|woff|woff2|ttf)$ {
        expires max;
        access_log off;
    }

    location ~ \.php$ {

        include snippets/fastcgi-php.conf;

        fastcgi_pass unix:/run/php/php8.1-fpm.sock;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        include fastcgi_params;

    }

    location ~ /\. {
        deny all;
    }

}
